name: Build and Deploy

on:
  push:
    branches: [main]

permissions:
  id-token: write
  contents: read

env:
  IMAGE: manaleeorpe/email-intelligence
  APP_NAME: fastapi-app
  RG: rg-fastapi

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Docker Hub login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build
        run: docker build -t $IMAGE:${{ github.sha }} .

      - name: Scan
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ${{ env.IMAGE }}:${{ github.sha }}
          severity: "CRITICAL,HIGH"
          exit-code: "0"
          ignore-unfixed: true

      - name: Push
        run: docker push $IMAGE:${{ github.sha }}

      - name: Azure login
        uses: azure/login@v2
        with:
          client-id: ${{ vars.AZURE_CLIENT_ID }}
          tenant-id: ${{ vars.AZURE_TENANT_ID }}
          subscription-id: ${{ vars.AZURE_SUBSCRIPTION_ID }}

      - name: Deploy revision
        run: |
          az containerapp update \
            -n $APP_NAME -g $RG \
            --image $IMAGE:${{ github.sha }}
